### PR TITLE
Add Caching Capabilities to Workflow [#17]

### PR DESCRIPTION
**Pull request by kokamkarsahil**
https://github.com/WasmEdge/docs/issues/17 Added cache using github action<sup>[1]</sup>

1. https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

### CODE REVIEW

**Comment by kokamkarsahil** [comment]
> @kokamkarsahil Could you please revert the changes to `package-lock.json` file?

Sure, I have reverted my changes 1789d94e9ea3e3663ca163683fdbecf500051c08 but it will result in CI fail as package.json and package-lock.json are out of sync so someone has to run `npm install` locally to sync this changes.

**Comment by adithyaakrishna** [comment]
@kokamkarsahil IMO this should be done from the maintainers side 👀 

CC @alabulei1

**Comment by kokamkarsahil** [comment]
> @kokamkarsahil IMO this should be done from the maintainers side eyes
> 
> CC @alabulei1

Agreed and issues like this can prevent using pre-commit hooks with [husky](https://github.com/typicode/husky)

**Review by alabulei1 — APPROVED** [review]

**Review by JYC0413 — APPROVED** [review]

**Comment by kokamkarsahil** [comment]
> Thanks @kokamkarsahil and @adithyaakrishna !

Happy to help out a bit!

**Pull request merged**
