### PR TITLE
[Bug] - Fixed Event Trigger Name

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

The workflow file had issue with a event trigger, this PR fixes the same

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by adithyaakrishna** [comment]
@alabulei1 Added a manual trigger in case any maintainer or admins want to trigger the workflow

**Review by alabulei1 — APPROVED** [review]

**Comment by alabulei1** [comment]
Hi  @adithyaakrishna 

Thanks. Could you explain to me how the manual trigger works?

**Comment by adithyaakrishna** [comment]
@alabulei1 Yes sure, the maintainers and admins can run the workflow by going to the actions tab, then going to the CodeQL Analysis workflow, then we will see a workflow_dispatch trigger note like the one in the below picture using which y'all can run the workflow manually

Screenshot 2023-05-17 at 11 54 06 AM

**Pull request merged**
