### PR TITLE
fix: typo in rustls plugin

### PR DESCRIPTION
**Pull request by morristai**
## Explanation

close: #212

## Related issue

- https://github.com/WasmEdge/WasmEdge/discussions/3182

## What type of PR is this

documentation

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by mhmohona — APPROVED** [review]
Good catch @morristai! 

However, the DCO check has failed. Please check to this for signing [DCO](https://www.secondstate.io/articles/dco/).

**Comment by morristai** [comment]
> Good catch @morristai!
> 
> However, the DCO check has failed. Please check to this for signing [DCO](https://www.secondstate.io/articles/dco/).

Done, thank you.

**Review by alabulei1 — APPROVED** [review]

**Comment by alabulei1** [comment]
Merged. Thank you @morristai and Happy Chinese New Year!

**Pull request merged**
