### PR TITLE
[Feat] - Migration of Content from Book to Docs - v2

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

This PR is a Continuation of #126

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by adithyaakrishna** [comment]
Fixing Build Failure due to broken links 👀

**Comment by adithyaakrishna** [comment]
@alabulei1 PR Ready for Review :)

**Comment by adithyaakrishna** [comment]
Also this PR adds Eslint Parser for MD [51cf778](https://github.com/WasmEdge/docs/pull/131/commits/51cf778360bebdff1871134642a7dd6db5c716f5)

**Comment by alabulei1** [comment]
HI @adithyaakrishna ,

Thanks for you work!

When WasmEdge acts as an embedded runtime, there is no need to use container tools like K8s to manage the WasmEdge apps. So Kubernetes file should be located in `develop`, not `embed`.

The use case under `embed` is to demonstrate how to embed WasmEdge into a Host application.

Could you move `Kubernetes` to `develop`? Thanks!

**Comment by adithyaakrishna** [comment]
@alabulei1 IMHO, having two sections for use-cases wouldn't make much sense. It may hurt our SEO and indexing also. Another thing, let's say that the users want to view use-cases of WasmEdge, we are giving them two options to decide which again will not retain many users. How about if we can club all the use-cases under one heading?

CC @juntao

**Comment by alabulei1** [comment]
We can change the name of the file folder. But the two use-case chapters aren't the same thing. We can't mix them together.

We can change the first `use case`'s name to `Kubernetes`, but it should be located in the `develop` category, not the `embed` category. As I explained before, when you embed WasmEdge into a host application, you don't need Kubernetes here. Thanks. @adithyaakrishna

**Review by alabulei1 — APPROVED** [review]

**Pull request merged**
