### PR TITLE
Add example for `wasm_bpf` plugin

### PR DESCRIPTION
**Pull request by Officeyutong**
Add an document page for the `wasm_bpf` plugin, demonstrating how to write programs use the API provided by that plugin

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by adithyaakrishna** [comment]
@Officeyutong The DCO check is failing, could you please sign-off your commits?

**Review by alabulei1 — APPROVED** [review]

**Comment by juntao** [comment]
This looks great! Can you also add a section on how to install the eBPF plugin here?

https://wasmedge.org/docs/develop/build-and-run/install/#install-wasmedge-with-plugins-1

Thanks.

**Comment by Officeyutong** [comment]
> This looks great! Can you also add a section on how to install the eBPF plugin here?
> 
> https://wasmedge.org/docs/develop/build-and-run/install/#install-wasmedge-with-plugins-1
> 
> Thanks.

The install script doesn't seem to support install wasm_bpf plugin yet, it only supports plugins with their names hardcoded in the script

**Comment by yunwei37** [comment]
Maybe we can open a pr and add the wasm_bpf plugin in it?

**Comment by alabulei1** [comment]
I will merge this first. When we have the installer for e-bpf plugin, the doc need to be updated.

**Pull request merged**
