### PR TITLE
Add more details for Windows MSVC build process.

### PR DESCRIPTION
**Pull request by am009**
## Explanation

I'm working on adding support of MSVC for WasmEdge. This adds related docs for this new feature.
See this issue https://github.com/WasmEdge/WasmEdge/issues/2629
See also this PR https://github.com/WasmEdge/WasmEdge/pull/2751

## What type of PR is this

> /kind documentation

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
Hi  @hydai 

Please help review this PR. Thanks.

**Comment by hydai** [comment]
I am going to review this after the major PR of this feature gets merged in the wasmedge repo.

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
The main PR is merged. We can process this now.

**Pull request merged**
