### PR TITLE
Add faq page and style guide

### PR DESCRIPTION
**Pull request by mhmohona**
## Explanation
Added faq page for Wasmedge

## Related issue
#37
Continuation of PR #198

## What type of PR is this
/kind documentation

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by adithyaakrishna — APPROVED** [review]
LGTM 🎉

**Comment by alabulei1** [comment]
Hi  @mhmohona 

It seems that #197 includes this PR.  Should I merge this PR?

**Comment by adithyaakrishna** [comment]
@mhmohona I guess this PR is very different from #197. The #197 PR adds testing docs while this PR adds the FAQs. IMHO, it would be good to have the faq page

CC @alabulei1 Could you please review it once again, as I personally feel, having a faq page for the project would be good

**Comment by mhmohona** [comment]
Hey @adithyaakrishna, thanks for your review! 
In above comment @alabulei1 meant #198 actually.

**Comment by alabulei1** [comment]
Hi @mhmohona 

could you please remove your faq page the style guide to  https://wasmedge.org/docs/start/overview. We have a separate chapter for getting started. Thanks!

**Review by alabulei1 — APPROVED** [review]

**Pull request merged**
