### PR TITLE
theme-test-build

### PR DESCRIPTION
**Pull request by Aryanryn09**
## build-fixed-for-theme

This commit is made after running the build server locally earlier the build failed.

## Proposed Changes

Screenshot 2023-04-30 175301
Screenshot 2023-04-30 183430
Screenshot 2023-04-30 183524

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@alabulei1 This PR changes all the colors of the docs or the whole theme, and I think we should decide on a color palette that aligns with WasmEdge Project and its colors.  Here are the screenshots of how it looks like wrt this PR

The HomePage background is pink and for this, we can use the color `#654FEF`

Screenshot 2023-05-09 at 12 36 04 PM

I feel we can use WasmEdgeRuntime Purple `#654FEF` here 

Screenshot 2023-05-09 at 12 36 56 PM

Hover link colors are not visible here as the background is black and link color is dark blue

Screenshot 2023-05-09 at 12 39 28 PM

On dark theme, the text is not clearly visible and might be confusing to some users

Screenshot 2023-05-09 at 12 43 06 PM

**Comment by Aryanryn09** [comment]
> @alabulei1 This PR changes all the colors of the docs or the whole theme, and I think we should decide on a color palette that aligns with WasmEdge Project and its colors. Here are the screenshots of how it looks like wrt this PR
> 
> The HomePage background is pink and for this, we can use the color `#654FEF`
> 
> Screenshot 2023-05-09 at 12 36 04 PM
> 
> I feel we can use WasmEdgeRuntime Purple `#654FEF` here
> 
> Screenshot 2023-05-09 at 12 36 56 PM
> 
> Hover link colors are not visible here as the background is black and link color is dark blue
> 
> Screenshot 2023-05-09 at 12 39 28 PM
> 
> On dark theme, the text is not clearly visible and might be confusing to some users
> 
> Screenshot 2023-05-09 at 12 43 06 PM

I think darker shade of blue, such as navy #654FEF / midnight blue #191970 or red orange for grabbing attention, can provide enough contrast with #654FEF to make links stand out without being too distracting.

**Comment by alabulei1** [comment]
#654FEF is great! So should I merge #45 first and then merge #51?

**Comment by alabulei1** [comment]
Hi  @Aryanryn09 

Since you haven't replied to me for a long time, I will close this PR first. Feel free to reopen this PR.

**Pull request closed without merging**
