### PR TITLE
Alabulei1 add llama2 inference

### PR DESCRIPTION
**Pull request by alabulei1**
Add docs for
1. llama2 inference with WasmEdge and Rust
2. install instruction for ggml backend
3. fix the typos in mediapipe

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by juntao** [comment]
1 We should download models from our HF repo now:

https://huggingface.co/wasmedge/llama2

2 I think it is easier to walkthrough the code for the `simple` example. And then explain / demo the `chat` and `api-server` examples. 

No need for code walkthrough for the latter two examples.

**Comment by alabulei1** [comment]
Hi @juntao 

The `simple` example is complicated too. https://github.com/second-state/llama-utils/blob/main/simple/src/main.rs

How about this one? https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/wasmedge-ggml-llama-interactive/src/main.rs  Will two different repos confuse readers?

**Comment by juntao** [comment]
The simple example should not have chat template. It should not support conversation history either. It should just let the user manually assemble a promote and it will output a string and exit. We will need to simplify it. 

The other example will be removed later. There cannot be two sources of truth.

**Comment by alabulei1** [comment]
> The simple example should not have chat template. It should not support conversation history either. It should just let the user manually assemble a promote and it will output a string and exit. We will need to simplify it.
> 
> The other example will be removed later. There cannot be two sources of truth.

@apepkuss Could you please check out the comments above -- simplify the `simple` example? Thanks.

**Comment by apepkuss** [comment]
Will update `simple`. Thanks a lot!

**Pull request closed without merging**
