### PR TITLE
Added links to plugins

### PR DESCRIPTION
**Pull request by Mash707**
#163

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by Mash707** [comment]
Hi @hydai , please have a look at this. Thank you

**Review by adithyaakrishna — CHANGES_REQUESTED** [review]
@Mash707 Could you please update the links here as well?

https://github.com/WasmEdge/docs/tree/main/i18n/zh/docusaurus-plugin-content-docs/current

**Comment by Mash707** [comment]
> @Mash707 Could you please update the links here as well?
> 
> https://github.com/WasmEdge/docs/tree/main/i18n/zh/docusaurus-plugin-content-docs/current

Sure I'll update it

**Review by adithyaakrishna — APPROVED** [review]
LGTM @hydai Could you please take another look at this?

**Review by hydai — APPROVED** [review]

**Pull request merged**
