### PR TITLE
Adds page in `/docs/talks`

### LINKED ISSUE #57: Feature Request: Create Page for WasmEdge talks
### Is your feature request related to a problem? Please describe.

As one who got to know about wasm-edge by watching talks, it's difficult to find all the wasm-edge related talks in one place.

### Describe the solution you'd like.

Create a `/talks` pages to list all the wasm-edge related talks in chronological order with related assets to talks like https://github.com/second-state/kubecon-eu-2023.

### Describe alternatives you've considered

Creating a YouTube playlist for all the talks.

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by kokamkarsahil**
## Explanation

This PR address #57 issue creating it as draft PR to add any left out talks.

## Related issue

Closes #57 Feature Request: Create Page for WasmEdge talks

## Proposed Changes

This PR adds following things:

1. `react-player` as dependency 1efad6e44d1e1845b386b92944bf227c3d9af48f

2. Adds `/docs/talks` page 161843ac8fffe0c67f1373f8d77144e86720da10

3. Removes example markdown page 534182cb278759e12e089d957a5666ed9ec254d1

Updated Changes:

4. Add custom CSS to avoid overflow on 6f65aa5dceea1aff042a3bfdd251973c267fbfc8

5. Fixed JSON syntax during broken during merge and updated package-lock.json to v3 format (if this commit needs to be revert let me as it does lots of changes) 6ee771df6a6b74f8ff1164528b472286af36345e

6. Added link to footer for `/talks` 85834b673ce37a6e9edb2753f33ac20a665e876c

## Preview changes

https://render.sahil.world/docs/talks

### CODE REVIEW

**Comment by alabulei1** [comment]
flows summarize

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by obridgedocs** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by alabulei1 — APPROVED** [review]

**Comment by alabulei1** [comment]
@kokamkarsahil  Thank you so much!

**Comment by kokamkarsahil** [comment]
> @kokamkarsahil Thank you so much!

Nope! Happy to help out.

**Comment by alabulei1** [comment]
@kokamkarsahil It seems that there're some conflicts.  Could you please fix the conflicts first?

**Comment by kokamkarsahil** [comment]
> @kokamkarsahil It seems that there're some conflicts. Could you please fix the conflicts first?

Done I have fixed those conflicts

**Pull request merged**
