### PR TITLE
Adds Wasm files builds links

### PR DESCRIPTION
**Pull request by kokamkarsahil**
## Explanation

This PR adds direct link to release files build on Github Actions check https://github.com/second-state/rust-examples/pull/1 for more info.

1. Adds direct link to the latest build files of WASM c59c911d189e7ce2c8fcbade38a681f97870bda0
2. Removes `static/files` directory along with it's content as it no longer needed d341504a7aa9c3e0bbcc26681652e4977d708f09
3. Synced changes to i18n file d50acfd1b8fe1e6a57dfa09c8b3395bb7227e61b

## Preview the affected paths

1. https://render.sahil.world/docs/develop/getting-started/quick_start
2. https://render.sahil.world/docs/zh/develop/getting-started/quick_start
3. https://render.sahil.world/docs/zh-TW/develop/getting-started/quick_start

### CODE REVIEW

**Comment by alabulei1** [comment]
@kokamkarsahil, thanks for your contribution. Sorry for my late reply. Could you please fix the conflict first? Thanks.

**Comment by kokamkarsahil** [comment]
> @kokamkarsahil, thanks for your contribution. Sorry for my late reply. Could you please fix the conflict first? Thanks.

Sure, no worries, I knew that the draft PR was going so I was too waiting for it to merge. I have resolved those conflicts!

Thank You!

**Review by alabulei1 — APPROVED** [review]

**Comment by alabulei1** [comment]
@juntao Could you take a look?

**Review by juntao — APPROVED** [review]
LGTM

**Pull request merged**
