### PR TITLE
Update wasm edge features

### PR DESCRIPTION
**Pull request by Aryanryn09**
## WasmEdge Features improved

Docs rephrased to make it more focused on the main topic of the text, which is the integration of WasmEdge with Kubernetes and  remove redundant information. The brief description of certain topics was done while making changes making it intuitive and user friendly while each options were kept unchanged.

## What type of PR is this
documentation

### CODE REVIEW

**Comment by alabulei1** [comment]
@Aryanryn09 Thanks for your contribution. Much appreciated.

Please make your DCO test pass firstly. I also have one question. Why did you delete CONTRIBUTING.md, LICENSE.md and CODE_OF_CONDUCT.md? Other than this, All are great!

**Comment by adithyaakrishna** [comment]
@Aryanryn09 You can fix the DCO by following the steps here, https://github.com/WasmEdge/docs/pull/34/checks?check_run_id=13058046664

Also, I am not sure why you deleted the 3 files as they are important for the project and CNCF says to add a License, COC file in a project repo. Could you please revert that change?

**Comment by adithyaakrishna** [comment]
@Aryanryn09 There seems to be a lot of conflicts wrt to the files changed, how about we close this PR and create a new one with your changes only?

**Comment by adithyaakrishna** [comment]
@Aryanryn09 IMHO we can revert the changes to CONTRIBUTING.md and package-lock.json file

**Comment by Aryanryn09** [comment]
> @Aryanryn09 There seems to be a lot of conflicts wrt to the files changed, how about we close this PR and create a new one with your changes only?

yes i think it would be great

**Pull request closed without merging**
