### PR TITLE
[Chore] - Fixed Markdown Lint and Removed Duplicated Code

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

- Adds superlinter workflow
- Removed duplicate run for build check
- Updated Dependency Review workflow

Fixes: #117

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by adithyaakrishna** [comment]
@alabulei1 Could you please review this PR?

**Comment by alabulei1** [comment]
Hi @adithyaakrishna 

Please fix the conflicts.

**Comment by adithyaakrishna** [comment]
@alabulei1 Done

**Comment by adithyaakrishna** [comment]
The linting seems to fail, will fix it asap

**Pull request closed without merging**
