### PR TITLE
[Feat] - Docs Upgrade - Linting and Pre-Commit Hooks

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

- This PR adds Eslint to Lint `.js | .jsx` files
- This PR adds Stylelint to Lint `.css | .scss` files
- This PR adds Husky for pre-commit hook config
- Fixes linting issues in JS and CSS files

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
@adithyaakrishna  There're some conflicts. Can you fix it first?

**Comment by adithyaakrishna** [comment]
@alabulei1 Done :)

**Review by alabulei1 — APPROVED** [review]

**Comment by alabulei1** [comment]
flows summarize

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
Hi  @adithyaakrishna,

Thanks. I have two questions:

1. What do you think about the following comment from ChatGPT? I'm not a JS developer, so I have to ask ChatGPT to help.

> However, there is a potential issue: the .prettierrc file does not have a newline at the end of the file, which could cause issues with some tools and editors. This should be fixed before merging the pull request.` 

2. Please fix the conflicts

**Comment by adithyaakrishna** [comment]
@alabulei1 Oops! My bad, I missed adding the new line, I have fixed it with the above commit. Thanks for pointing it out :)

and I have fixed the conflicts also 👀

**Comment by alabulei1** [comment]
So ChatGPT's reviews are right?

**Comment by adithyaakrishna** [comment]
@alabulei1 Yes, in this case, it is right. I am not sure about all the cases in the future, but the issue pointed out by ChatGPT is correct here

**Comment by adithyaakrishna** [comment]
@alabulei1 I really like the pr-summary bot, but I feel sometimes its a bit too long to go through. I checked the repo for the same at, https://github.com/flows-network/github-pr-summary/blob/main/src/github-pr-summary.rs#L187 and I had this idea, what if the body is collapsible for each commit description?

For example, instead of like this, 

### [Commit ef6e443e817a0b07a1d53756fe79dce2bb9474cc](https://github.com/WasmEdge/WasmEdge/pull/67/commits/ef6e443e817a0b07a1d53756fe79dce2bb9474cc)
The patch adds several packages including ESLint, Stylelint, Prettier, and Husky. It also includes updates to the dependencies in package-lock.json. There appear to be no conflicts with the changes and no potential problems are immediately evident. However, it would be worthwhile to review the configuration and implementation of the new packages and make sure they are integrated properly with existing code. It would also be useful to assess if this patch introduces any regressions or performance issues and if any additional testing or optimization is necessary.


**How does this look?**

<details>
  <summary>[Commit ef6e443e817a0b07a1d53756fe79dce2bb9474cc](https://github.com/WasmEdge/WasmEdge/pull/67/commits/ef6e443e817a0b07a1d53756fe79dce2bb9474cc)</summary>
  
  The patch adds several packages including ESLint, Stylelint, Prettier, and Husky. It also includes updates to the dependencies in package-lock.json. There appear to be no conflicts with the changes and no potential problems are immediately evident. However, it would be worthwhile to review the configuration and implementation of the new packages and make sure they are integrated properly with existing code. It would also be useful to assess if this patch introduces any regressions or performance issues and if any additional testing or optimization is necessary.
  
</details>

**Comment by adithyaakrishna** [comment]
This was just a random thought that came to my mind 😶

**Comment by alabulei1** [comment]
> @alabulei1 I really like the pr-summary bot, but I feel sometimes its a bit too long to go through. I checked the repo for the same at, https://github.com/flows-network/github-pr-summary/blob/main/src/github-pr-summary.rs#L187 and I had this idea, what if the body is collapsible for each commit description?
> 
> For example, instead of like this,
> 
> ### [Commit ef6e443e817a0b07a1d53756fe79dce2bb9474cc](https://github.com/WasmEdge/WasmEdge/pull/67/commits/ef6e443e817a0b07a1d53756fe79dce2bb9474cc)
> The patch adds several packages including ESLint, Stylelint, Prettier, and Husky. It also includes updates to the dependencies in package-lock.json. There appear to be no conflicts with the changes and no potential problems are immediately evident. However, it would be worthwhile to review the configuration and implementation of the new packages and make sure they are integrated properly with existing code. It would also be useful to assess if this patch introduces any regressions or performance issues and if any additional testing or optimization is necessary.
> 
> **How does this look?**
> 
> Commit [ef6e443](https://github.com/WasmEdge/docs/commit/ef6e443e817a0b07a1d53756fe79dce2bb9474cc)

This format looks great! We can also ask ChatGPT only give a summary.

**Comment by juntao** [comment]
Hi @adithyaakrishna 

The collapsible commit sections look great! Can you raise a PR to the main branch of the bot template repo? https://github.com/flows-network/github-pr-summary

Thanks!

**Comment by adithyaakrishna** [comment]
@juntao How abt we give the users of the bot an option or param to enable or disable collapsible commit description?

so that, instead of just one format, users customize how they want it and by setting `collapsibleCommitDescription=true` they will have the new format

**Comment by juntao** [comment]
Good idea! 

Our current approach is to make the template as simple as possible. If the user wants to make changes, he can change his local copy of the bot source code. 

So, let's make it easy to switch between collapsed and expanded commits in the code -- perhaps using variables like `MODEL` but not expose it as an environment var for the template. Thanks.

**Pull request merged**
