### PR TITLE
Fixed Build Step

### LINKED ISSUE #78: The latest CI fails
### Describe the bug.

The latest CI fails https://github.com/WasmEdge/docs/actions/runs/5066235102/jobs/9095783281

### Describe the steps to reproduce the behavior.

_No response_

### Expected behavior.

_No response_

### Screenshots.

_No response_

### Operating Environment

GitHub Action

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by kokamkarsahil**
## Explanation

Added 1e0a76042cbe6c216afda1a9143383eb39973bb9 which lead to build fail

## Related issue

Closes #78

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by adithyaakrishna** [comment]
@kokamkarsahil Its not adviced to add a package just like that, there should be a use of it. We may have to dive a bit deeper on why this is happening

More Info: https://github.com/facebook/docusaurus/issues/7532

**Comment by kokamkarsahil** [comment]
> @kokamkarsahil Its not adviced to add a package just like that, there should be a use of it. We may have to dive a bit deeper on why this is happening

It's needed as the workflow runs on Ubuntu it clearly states it's needed to build in the ERROR Message as it was missing

https://github.com/WasmEdge/docs/blob/e6ef484b855776822d77d2db21fc6fe3a14d7470/.github/workflows/deploy.yml#L17-L19

> More Info: [facebook/docusaurus#7532](https://github.com/facebook/docusaurus/issues/7532)

That's unrelated issue you can check the error of the issue with the other one

The error which is mentioned there:

```
[ERROR] Unable to build website for locale en.
[ERROR] TypeError: pathname.match is not a function
```

The error we are getting:
```
Error:  Unable to build website for locale en.
Error:  Error: Cannot find module '@node-rs/jieba-linux-x64-gnu'
```

Can you please clarify why you mentioned that issue.

Thank You!

**Comment by adithyaakrishna** [comment]
Also, do you mind running the Deploy CI on your fork to check if the build runs perfectly?

**Comment by adithyaakrishna** [comment]
@kokamkarsahil This PR looks good to me, we can add this package itself, sorry for the confusion :)

**Comment by adithyaakrishna** [comment]
This fails on windows too

**Comment by kokamkarsahil** [comment]
> Do we really need to check in the lock file? It seems excessive to have several hundreds lines of changes in the lock file.

We can remove the need of lock file but it will introduction unexpected dependency from any package without our knowledge which can affect the build.

**Comment by kokamkarsahil** [comment]
> This fails on windows too

Sorry for that that wasn't bug I added only supported for Ubuntu as we are using it.

**Comment by kokamkarsahil** [comment]
> @kokamkarsahil This PR breaks the docs being built and prevents running `npm install` on macOS ARM CPUs

Can you check now if the build fails again on all your systems you want to build?

## It should support build on the following matrix now

|                  | node12 | node14 | node16 | node18 |
| ---------------- | ------ | ------ | ------ | ------ |
| Windows x64      | ✓      | ✓      | ✓      | ✓      |
| Windows x32      | ✓      | ✓      | ✓      | ✓      |
| Windows arm64    | ✓      | ✓      | ✓      | ✓      |
| macOS x64        | ✓      | ✓      | ✓      | ✓      |
| macOS arm64      | ✓      | ✓      | ✓      | ✓      |
| Linux x64 gnu    | ✓      | ✓      | ✓      | ✓      |
| Linux x64 musl   | ✓      | ✓      | ✓      | ✓      |
| Linux arm gnu    | ✓      | ✓      | ✓      | ✓      |
| Linux arm64 gnu  | ✓      | ✓      | ✓      | ✓      |
| Linux arm64 musl | ✓      | ✓      | ✓      | ✓      |
| Android arm64    | ✓      | ✓      | ✓      | ✓      |
| Android armv7    | ✓      | ✓      | ✓      | ✓      |
| FreeBSD x64      | ✓      | ✓      | ✓      | ✓      |

Thank You!

**Review by juntao — APPROVED** [review]
LGTM

**Pull request merged**
