### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Preshh0**
I fixed the numbering on the README.md file and clarified some steps in the git process.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@Preshh0 DCO is failing, could you please sign-off the commits?

**Comment by Preshh0** [comment]
Oh wow, I thought I did that. 
Let me fix it.

**Comment by Preshh0** [comment]
Done @adithyaakrishna. I'm not sure why it's still failing.

**Comment by adithyaakrishna** [comment]
@Preshh0 You gotta rebase and force push it to solve the issue 👀

**Comment by Preshh0** [comment]
I used this method - "git commit --amend -s " and force pushed, but I'd try rebase too just incase.

**Comment by alabulei1** [comment]
@Preshh0 To fix the DCO test, you can just follow the instructions by DCO details https://github.com/WasmEdge/docs/pull/25/checks?check_run_id=12957887656 Or you can also follow this article https://www.secondstate.io/articles/dco/

**Comment by Preshh0** [comment]
Fixed!

**Comment by adithyaakrishna** [comment]
@Preshh0 Could you please resolve the conflicts?

**Comment by Preshh0** [comment]
Done.

**Review by Swatishree-Mahapatra — COMMENTED** [review]
There is a change in the package-lock.json file. As per my understanding, it might not be a required change. Please look into it.

**Comment by adithyaakrishna** [comment]
@Preshh0 I agree with @Swatishree-Mahapatra 's comment, could you pls revert that change?

**Comment by Preshh0** [comment]
I think I've fixed it now. I'm sorry about that.

**Comment by adithyaakrishna** [comment]
@Preshh0 The file seems to be still there 👀

**Comment by Preshh0** [comment]
I think i'd just close this PR.

**Pull request closed without merging**
