### PR TITLE
update loadable plugin section

### PR DESCRIPTION
**Pull request by mhmohona**
## Explanation
Update Loadable Plug-in section - expanded explanation and added flowchart for better understanding of the workflow. Also updated as per Yi-Ying's review. 

Reopening PR https://github.com/WasmEdge/docs/pull/86 for passing DOC test

## What type of PR is this
/kind documentation

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@alabulei1 CI Workflows need your approval to run. Its a default feature of GH Actions. More Info: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Review by alabulei1 — APPROVED** [review]

**Comment by adithyaakrishna** [comment]
@mhmohona Lint check failing here 👀

**Comment by mhmohona** [comment]
@adithyaakrishna yes, its the same error I am getting all my PRs. I am unable to fix it. :3

**Comment by adithyaakrishna** [comment]
@mhmohona There seems to be linting issues in many files which were not changed, I have created a PR #109 to fix the CI and linting issues :)

**Comment by alabulei1** [comment]
Hi  @mhmohona 

Still have one CI that didn't pass. Could you fix again?

**Comment by mhmohona** [comment]
@alabulei1  I hope cli check will pass now.

**Comment by adithyaakrishna** [comment]
@alabulei1 The workflows need to be approved manually for it to run 😶

**Review by alabulei1 — APPROVED** [review]

**Comment by alabulei1** [comment]
@mhmohona The lint CI passed! But the DCO tests failed. Could you please take a look again? Thanks.

**Pull request closed without merging**
