### PR TITLE
[Bug] - Fixes CodeQL Workflow

### LINKED ISSUE #78: The latest CI fails
### Describe the bug.

The latest CI fails https://github.com/WasmEdge/docs/actions/runs/5066235102/jobs/9095783281

### Describe the steps to reproduce the behavior.

_No response_

### Expected behavior.

_No response_

### Screenshots.

_No response_

### Operating Environment

GitHub Action

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

- Fixes CodeQL Workflow

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
Still fails, checking on it :/

**Comment by adithyaakrishna** [comment]
@alabulei1 CI Runs successfully on my fork :)

- Test Run 1 - https://github.com/adithyaakrishna/wasmedge-docs/actions/runs/5070223433
- Test Run 2 - https://github.com/adithyaakrishna/wasmedge-docs/actions/runs/5070413095

**Comment by juntao** [comment]
Hmm, why do we run the CI on macOS? 😅 Does ubuntu not work? Thanks.

**Comment by adithyaakrishna** [comment]
@juntao Its due to the dependency issue of @node-rs/jieba, the [gnu version](https://www.npmjs.com/package/@node-rs/jieba-linux-x64-gnu) of the package isnt built which is a dependency of `@easyops-cn/docusaurus-search-local` package. I will create a issue at https://github.com/easyops-cn/docusaurus-search-local so that the team can look into this more

The fix is just a temp one, we can re-change it back to ubuntu in the future. IMO it wouldnt matter much as we are just building and pushing the package to another repo.

**Comment by kokamkarsahil** [comment]
> 

Adding `@node-rs/jieba`  as dependency can also solve this issue https://github.com/WasmEdge/docs/pull/79

**Comment by juntao** [comment]
It seems that #79 is a simpler solution. Does it have a problem? Thanks!

**Comment by adithyaakrishna** [comment]
@juntao @alabulei1 Updated this PR to fix CodeQL Workflow only, the other chanegs have been reverted

**Review by juntao — APPROVED** [review]
Thanks!

**Pull request merged**
